Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu20044liveserver"
  config.vm.define "ubuntu2004worker02"
  config.vm.hostname = "ubuntu2004worker02"

  config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "ubuntu2004worker02"
    vb.memory = 2048
    vb.cpus = 2
  end

end
