Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu20044liveserver"
  config.vm.define "ubuntu20044workernode02"
  config.vm.hostname = "ubuntu20044workernode02"

  config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "ubuntu20044workernode02"
    vb.memory = 2048
    vb.cpus = 1
  end

end
