Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu20044liveserver"
  config.vm.define "ubuntu20044liveserver"
  config.vm.hostname = "ubuntu20044liveserver"

  config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "ubuntu20044liveserver"
    vb.memory = 4096
    vb.cpus = 1
  end

end
